from dataclasses import dataclass
from typing import Protocol

from webauthn.registration.verify_registration_response import VerifiedRegistration


@dataclass
class WebauthnCredential:
    id: bytes  # unique credential identifier, generated by the authenticator
    public_key: bytes  # public key used to verify authentication signatures
    signature_count: int  # incremented on each use, helps detect cloned authenticators
    user_id: int  # owner of this credential

    @staticmethod
    def from_registration_and_user(registration: VerifiedRegistration,
        user: User) -> WebauthnCredential:
        return WebauthnCredential(
            id=registration.credential_id,
            public_key=registration.credential_public_key,
            signature_count=registration.sign_count,
            user_id=user.id,
        )


@dataclass
class RelyingParty:
    id: str  # domain name (e.g. "localhost")
    name: str  # human-readable name, displayed by the authenticator
    origin: str


@dataclass
class User:
    id: int
    username: str
    display_name: str
    user_handle: bytes  # random opaque identifier used during WebAuthn ceremonies


class PasskeyStorage(Protocol):
    def save_passkey(self, credential: WebauthnCredential) -> None:
        ...

    def get_passkey(self, credential_id: bytes) -> WebauthnCredential:
        ...

    def update_signature_count(self, passkey_id: bytes, signature_count: int): ...
